---
- name: Deploy IPTables Rules for JBOSS
  template:
    src: iptables-save # could it be fetched from vsts
    dest: /etc/sysconfig/iptables # ??
  when: ansible_distribution_major_version != "7"
  
- name: Ensure that firewalld is installed